name: hooks
version: 0.0.1
author: Ewetumo Alexander Adeniyi <trinoxf@gmail.com>
repository: https://github.com/influx6/hooks
description: a low-level api for hooking into your objects
dependencies:
 ds:
  path: ../ds
 hub:
  path: ../hub
 invocable:
  path: ../invocable

