name: hooks
version: 0.2.0
author: Ewetumo Alexander Adeniyi <trinoxf@gmail.com>
homepage: https://github.com/influx6/hooks
description: a low-level api for hooking into your objects
#dependencies:
#  invocable: any
#  hooks: any
dev_dependencies:
  invocable:
    path: ../invocable
  hub:
    path: ../hub
